# Generated by Django 5.0.6 on 2024-06-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
